### ISSUE TITLE
Self-supervised pretrained model link.

### ISSUE THREAD

**Issue by Tramac** [amazon-research/video-contrastive-learning#4]
@bryanyzhu Hi, thank you for your excellent work! Is there a link to the Self-supervised pretrained model?
Looking forward to your reply!

**Comment by bryanyzhu** [comment]
Hi, you mean the self-supervised pretrained model on Kinetics400 training set? It is in the `linear evaluation` section of `README`. I attach its link here as well, https://haofeik-data.s3.amazonaws.com/VCLR/pretrained/vclr_k400.pth
