### ISSUE TITLE
About frame extract failed

### ISSUE THREAD

**Issue by AllenPu** [amazon-research/video-contrastive-learning#7]
Hi,
     Sorry for troubling you again, I ran the ./tools/data/k400/extract_frames.py , however, some of the videos which empty or very small or have some error(cannot be opened) would cause into fail frame extraction and leave an empty folder, will that affect the training?

**Comment by KuangHaofei** [comment]
Hi, sorry for the late response! Actually, I also meet the problem, it is caused by the video file being broken or could not found the video.
I think it is common problem with the K400, I think you can ignore it current, and you will get the same dataset with us if you follow our tutorials.
Thanks!
