### ISSUE TITLE
In script shell/eval_retrieval.sh

### ISSUE THREAD

**Issue by AllenPu** [amazon-research/video-contrastive-learning#8]
In line 34, is that should be python3 eval_retrieve_knn_pred.py instead of python3 eval_retrieval_knn_pred.py?
It seems no file named eval_retrieval_knn_pred.py

**Comment by AllenPu** [comment]
and should be bash shell/eval_retrieve.sh?

**Comment by KuangHaofei** [comment]
Yes, it is! Sorry for the typo, we will fix it later!
Thanks for your reminder!

**Comment by bryanyzhu** [comment]
Hi @KuangHaofei , just curious, will there be a PR to fix this? Thank you.

**Comment by KuangHaofei** [comment]
> 

Sorry! I have submitted a new PR for the issue! Please check #10, thanks!

**Comment by bryanyzhu** [comment]
Thanks, just merged.
