### ISSUE TITLE
In script shell/main_train.sh

### ISSUE THREAD

**Issue by wangll1212** [amazon-research/video-contrastive-learning#9]
Hi, I want to pretrain the self-supervised model on ucf101. In line 17, what should the value parameter --dataset be changed to ?

**Comment by KuangHaofei** [comment]
Hi,

The [KineticsClipFolderDatasetOrderTSN](https://github.com/amazon-research/video-contrastive-learning/blob/9a8d0473fd938dd77dfa6db2762abbc567da040e/dataset/dataset_kinetics.py#L114) class defines our strategy about how to generate the positive pairs. But its base class [KineticsClipFolderDataset](https://github.com/amazon-research/video-contrastive-learning/blob/9a8d0473fd938dd77dfa6db2762abbc567da040e/dataset/dataset_kinetics.py#L27) just could be used for the data format like the Kinetics dataset.

Suppose you want to pretrain the model on UCF101. In that case, you need to define a base class to load the frames and create the `self.samples` variable (see [line 123 of dataset_kinetics.py](https://github.com/amazon-research/video-contrastive-learning/blob/9a8d0473fd938dd77dfa6db2762abbc567da040e/dataset/dataset_kinetics.py#L123). Then, you can follow the KineticsClipFolderDatasetOrderTSN class to generate positive pairs for pertaining.

Hope it helps you!
Thanks!

**Comment by wangll1212** [comment]
Thank you very much for your reply, that really helps!
